plugins {
    `java-library`
    alias(libs.plugins.blossom)
}

group = "net.minestom"
version = "dev"
description = "1.21 Lightweight Minecraft server"

repositories {
    mavenLocal()
    mavenCentral()
}

configurations.all {
    // We only use Jetbrains Annotations
    exclude("org.checkerframework", "checker-qual")
}

java {
    withSourcesJar()
    withJavadocJar()

    toolchain.languageVersion = JavaLanguageVersion.of(25)
}

sourceSets {
    main {
        java {
            srcDir(file("src/main/java"))
            srcDir(file("src/autogenerated/java"))
        }
        blossom {
            javaSources {
                val group = project.group as String?
                val artifact = project.name as String?
                property("COMMIT", "LOCAL")
                property("BRANCH", "LOCAL")
                property("GROUP", group ?: "UNKNOWN")
                property("ARTIFACT", artifact ?: "UNKNOWN")
                property("VERSION", project.version.toString())
            }
        }
    }
}

dependencies {
    // Core dependencies
    api(libs.bundles.adventure)
    implementation(libs.slf4j)
    implementation(libs.minestomData)

    // Performance/data structures
    implementation(libs.fastutil)
    implementation(libs.bundles.flare)
    api(libs.gson)
    implementation(libs.jcTools)
}

tasks {
    withType<Zip> {
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }

    withType<Test> {
        useJUnitPlatform()

        // Viewable packets make tracking harder. Could be re-enabled later.
        jvmArgs("-Dminestom.viewable-packet=false")
        jvmArgs("-Dminestom.inside-test=true")
        minHeapSize = "512m"
        maxHeapSize = "1024m"
    }

    withType<JavaCompile> {
        options.encoding = "UTF-8"
    }

    jar {
        manifest {
            attributes("Automatic-Module-Name" to "net.minestom.server")
        }
    }
}
